version: '3.8'

services:
  # --- Módulo de Back-end (FastAPI) ---
  api:
    build: .
    container_name: vera_api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      # Sobrescreve o host do banco para apontar para o container do postgres na rede interna do Docker
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      - POSTGRES_SERVER=postgres

  # --- Banco de Dados Relacional (PostgreSQL) ---
  postgres:
    image: postgres:15
    container_name: vera_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data